### ISSUE TITLE
There seems to be something wrong with this command.

### ISSUE THREAD

**Issue by 120829** [jzr99/DNF-Avatar#2]
There seems to be something wrong with this command.
```
Generate Distillation Avatar

To generate pseudo ground truth image used for distillation, use the following command:

python launch_ps.py training_mode=teacher \
   implicit_branch.mode=test \
   implicit_branch.resume=./exp/intrinsic-avatar-male-3-casual/male-3-casual/ckpt/epoch=219-step=25000.ckpt \
   implicit_branch.dataset=animation/male-3-casual-tpose \
   implicit_branch.tag=male-3-casual-tpose

Then, the generated distillation avatar will be saved under the directory exp/intrinsic-avatar-male-3-casual/male-3-casual-tpose
```

**Comment by jzr99** [comment]
Hi thank you for your interests!

I'll go through the whole pipeline and fix it later this week.

Best,
Zeren

**Comment by 120829** [comment]
> Hi thank you for your interests!谢谢您的关注！
> 
> I'll go through the whole pipeline and fix it later this week.我会检查整个管道，并在本周晚些时候修复它。
> 
> Best,  最好的， Zeren  泽仁

Thank you very much for taking the time to reply to this comment. I sincerely look forward to your updates.

**Comment by jzr99** [comment]
Hi,

I just go through the whole pipeline and it should work now. Please delete your previous `exp` folder and follow the new version of README and start from teacher training again.

Best,
Zeren

**Comment by 120829** [comment]
While training the student model, I followed the documentation instructions and noticed that the poses folder was missing (I processed the dataset using the InstantAvatar script). I wrote custom code to generate the train.npz and val.npz files. However, when testing the student model, I encountered an error indicating that the anim_nerf_train.npz file was still missing.

**Comment by jzr99** [comment]
Hi,

You can download the processed dataset `male-3-causual.zip` directly from the [google drive](https://drive.google.com/drive/folders/1OjA_Ho-IctUW4itN1mO2d5OELLJcMvpd?usp=drive_link) which contain the `anim_nerf_train.npz` (which is a more well-aligned pose used by anim_nerf compared with train.npz).

Best,
Zeren

**Comment by 120829** [comment]
> 你好
> 
> 您可以直接从 [google drive](https://drive.google.com/drive/folders/1OjA_Ho-IctUW4itN1mO2d5OELLJcMvpd?usp=drive_link) 下载处理后的数据集，其中包含（与 train.npz 相比，这是 anim_nerf 使用的更对齐的姿势）。`male-3-causual.zip``anim_nerf_train.npz`
> 
> Best， 泽仁

I have submitted the application. Kindly review it at your earliest convenience.

**Comment by jzr99** [comment]
Sorry I forget to change the permission to public.

Please try this new link again!

[google drive](https://drive.google.com/drive/folders/1ZgajfGd3bgwPdXLPyp6d1eJleoIqrx7Q?usp=sharing)

**Comment by 120829** [comment]
> Sorry I forget to change the permission to public.抱歉，我忘记将权限更改为 public。
> 
> Please try this new link again!请再次尝试此新链接！
> 
> [google drive  谷歌驱动器](https://drive.google.com/drive/folders/1ZgajfGd3bgwPdXLPyp6d1eJleoIqrx7Q?usp=sharing)

Thank you very much for your help. I have successfully obtained the results.
